repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
    - id: pylint
      name: pylint
      entry: make lint
      language: system
      types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
    - id: debug-statements
